function varargout = CTCF(filepath,NumberOfZPoints)
% Calculates the corrected total cell fluorescence (CTCF) for all ROIs at 
% all Z-planes, then performs ratiometric analysis to see the RFP/GFP ratio 
% to use as a readout of ISR state
% 
% Requires a complete analyzed dataset as generated by measureROIs.m 	
%
% INPUTS:
%   filepath: path to image analysis folders
%   NumberOfZPoints: from image metadata
%
% OUTPUTS:
%   ratio: cell array containing the ratios of RFP/GFP fluorescence for all ROIs at all Z-planes after correcting for total cell fluorescence
%   gfpCTCF: cell array containing CTCF values for all ROIs at all Z-planes in the GFP channel
%   rfpCTCF: cell array containing CTCF values for all ROIs at all Z-planes in the RFP channel

% Written by Kayla Fernando (kayla.fernando@duke.edu) (4/26/23)

% Size of cell array will reflect number of Z-planes
% Each array element will contain the measurements of all ROIs selected at that Z-plane
gfpCTCF = cell(1,NumberOfZPoints);
rfpCTCF = cell(1,NumberOfZPoints);
ratio = cell(1,NumberOfZPoints);

% For each Z-plane
for k = 1:NumberOfZPoints
    % Get the GFP results
    gfpResults = readmatrix([filepath '\GFPresults\Results' num2str(k) '.csv']); 
        gfpNames = detectImportOptions([filepath '\GFPresults\Results' num2str(k) '.csv']).VariableNames;
    % Get the RFP results
    rfpResults = readmatrix([filepath '\RFPresults\Results' num2str(k) '.csv']); % get the RFP results
        rfpNames = detectImportOptions([filepath '\RFPresults\Results' num2str(k) '.csv']).VariableNames;
    % How many ROIs are at this Z-plane
    NumberofROIs = size(gfpResults,1);
    % Go through each ROI
    for n = 1:NumberofROIs
        % GFP: (integrated density - (area of selected cell * mean fluorescence of background readings)) / area
%        gfpCTCF{k}(n) = (gfpResults(n,find(strcmp(gfpNames,'IntDen'))) - ...
%            (gfpResults(n,find(strcmp(gfpNames,'Area'))) * mean(gfpResults(end-2:end,find(strcmp(gfpNames,'Mean')))))) / ...
%            gfpResults(n,find(strcmp(gfpNames,'Area')));
        gfpCTCF{k}(n) = (gfpResults(n,find(strcmp(gfpNames,'IntDen'))) - mean(gfpResults(end-2:end,find(strcmp(gfpNames,'Mean'))))); % basic formula
        % RFP: (integrated density - (area of selected cell * mean fluorescence of background readings)) / area
%        rfpCTCF{k}(n) = (rfpResults(n,find(strcmp(rfpNames,'IntDen'))) - ...
%            (rfpResults(n,find(strcmp(rfpNames,'Area'))) * mean(rfpResults(end-2:end,find(strcmp(rfpNames,'Mean')))))) / ...
%            rfpResults(n,find(strcmp(rfpNames,'Area')));
        rfpCTCF{k}(n) = (rfpResults(n,find(strcmp(rfpNames,'IntDen'))) - mean(rfpResults(end-2:end,find(strcmp(rfpNames,'Mean'))))); % basic formula
        % Ratiometric analysis with CTCF
        ratio{k}(n) = rfpCTCF{k}(n)/gfpCTCF{k}(n);
    end
end

if nargout > 0
    varargout{1} = ratio;
    varargout{2} = gfpCTCF;
    varargout{3} = rfpCTCF;
end

end
